from datetime import datetime, timedelta

from freeradius.models import AttributeOpValue, Group, Nas, User, UserGroup
from freeradius.repositories import GroupRepository, NasRepository, UserRepository
from freeradius.settings import RadTables

from database import db_connect

# Load the FreeRADIUS repositories
db_connection = db_connect()
user_repo = UserRepository(db_connection)
group_repo = GroupRepository(db_connection)
nas_repo = NasRepository(db_connection)

# Add some NASes
n1 = Nas(nasname="3.3.3.3", shortname="my-super-nas", secret="my-super-secret")
n2 = Nas(nasname="4.4.4.4", shortname="my-other-nas", secret="my-other-secret")
if not nas_repo.exists(n1.nasname) and not nas_repo.exists(n2.nasname):
    nas_repo.add(n1)
    nas_repo.add(n2)

# Add some groups
g1 = Group(groupname="100m", replies=[AttributeOpValue(attribute="Filter-Id", op=":=", value="100m")])
g2 = Group(groupname="200m", replies=[AttributeOpValue(attribute="Filter-Id", op=":=", value="200m")])
if not group_repo.exists(g1.groupname) and not group_repo.exists(g2.groupname):
    group_repo.add(g1)
    group_repo.add(g2)

# Add some users
u1 = User(
    username="bob",
    groups=[UserGroup(groupname=g1.groupname)],
    checks=[AttributeOpValue(attribute="Cleartext-Password", op=":=", value="bob-pass")],
    replies=[
        AttributeOpValue(attribute="Framed-IP-Address", op=":=", value="10.0.0.1"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.1.0/24"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.2.0/24"),
        AttributeOpValue(attribute="Huawei-Vpn-Instance", op=":=", value="bob-vrf"),
    ],
)
u2 = User(
    username="alice@adsl",
    groups=[UserGroup(groupname=g1.groupname)],
    checks=[AttributeOpValue(attribute="Cleartext-Password", op=":=", value="alice-pass")],
    replies=[
        AttributeOpValue(attribute="Framed-IP-Address", op=":=", value="10.0.0.2"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.1.0/24"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.2.0/24"),
        AttributeOpValue(attribute="Huawei-Vpn-Instance", op=":=", value="alice-vrf"),
    ],
)
u3 = User(
    username="eve",
    groups=[UserGroup(groupname=g1.groupname, priority=1), UserGroup(groupname=g2.groupname, priority=2)],
    checks=[AttributeOpValue(attribute="Cleartext-Password", op=":=", value="eve-pass")],
    replies=[
        AttributeOpValue(attribute="Framed-IP-Address", op=":=", value="10.0.0.3"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.1.0/24"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.2.0/24"),
        AttributeOpValue(attribute="Huawei-Vpn-Instance", op=":=", value="eve-vrf"),
    ],
)
u4 = User(
    username="oscar@wil.de",
    checks=[AttributeOpValue(attribute="Cleartext-Password", op=":=", value="oscar-pass")],
    replies=[
        AttributeOpValue(attribute="Framed-IP-Address", op=":=", value="10.0.0.4"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.1.0/24"),
        AttributeOpValue(attribute="Framed-Route", op="+=", value="192.168.2.0/24"),
        AttributeOpValue(attribute="Huawei-Vpn-Instance", op=":=", value="oscar-vrf"),
    ],
)
if (
    not user_repo.exists(u1.username)
    and not user_repo.exists(u2.username)
    and not user_repo.exists(u3.username)
    and not user_repo.exists(u4.username)
    and group_repo.exists(g1.groupname)
    and group_repo.exists(g2.groupname)
):
    user_repo.add(u1)
    user_repo.add(u2)
    user_repo.add(u3)
    user_repo.add(u4)

# Add some example radacct records (accounting sessions)
# These are typically generated by FreeRADIUS, but we add some for testing/demo purposes
rad_tables = RadTables()
cursor = db_connection.cursor()

# Check if radacct table has any records
cursor.execute(f"SELECT COUNT(*) FROM {rad_tables.radacct}")
(radacct_count,) = cursor.fetchone()

if radacct_count == 0:
    now = datetime.now()
    
    # Bob's sessions - one active, two completed
    radacct_records = [
        # Bob - active session (no stop time)
        {
            "acctsessionid": "bob-session-001",
            "acctuniqueid": "bob-unique-001",
            "username": "bob",
            "nasipaddress": "3.3.3.3",
            "acctstarttime": (now - timedelta(hours=2)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctupdatetime": now.strftime("%Y-%m-%d %H:%M:%S"),
            "acctstoptime": None,
            "acctsessiontime": 7200,
            "acctinputoctets": 150000000,
            "acctoutputoctets": 2500000000,
            "framedipaddress": "10.0.0.1",
            "calledstationid": "00:11:22:33:44:55",
            "callingstationid": "AA:BB:CC:DD:EE:FF",
            "acctterminatecause": "",
        },
        # Bob - completed session from yesterday
        {
            "acctsessionid": "bob-session-002",
            "acctuniqueid": "bob-unique-002",
            "username": "bob",
            "nasipaddress": "3.3.3.3",
            "acctstarttime": (now - timedelta(days=1, hours=5)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctstoptime": (now - timedelta(days=1, hours=2)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctsessiontime": 10800,
            "acctinputoctets": 500000000,
            "acctoutputoctets": 8000000000,
            "framedipaddress": "10.0.0.1",
            "acctterminatecause": "User-Request",
        },
        # Alice - active session
        {
            "acctsessionid": "alice-session-001",
            "acctuniqueid": "alice-unique-001",
            "username": "alice@adsl",
            "nasipaddress": "4.4.4.4",
            "acctstarttime": (now - timedelta(hours=1)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctupdatetime": now.strftime("%Y-%m-%d %H:%M:%S"),
            "acctstoptime": None,
            "acctsessiontime": 3600,
            "acctinputoctets": 75000000,
            "acctoutputoctets": 1200000000,
            "framedipaddress": "10.0.0.2",
            "acctterminatecause": "",
        },
        # Eve - completed session
        {
            "acctsessionid": "eve-session-001",
            "acctuniqueid": "eve-unique-001",
            "username": "eve",
            "nasipaddress": "3.3.3.3",
            "acctstarttime": (now - timedelta(days=2)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctstoptime": (now - timedelta(days=2) + timedelta(hours=8)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctsessiontime": 28800,
            "acctinputoctets": 1000000000,
            "acctoutputoctets": 15000000000,
            "framedipaddress": "10.0.0.3",
            "acctterminatecause": "Session-Timeout",
        },
        # Eve - another completed session
        {
            "acctsessionid": "eve-session-002",
            "acctuniqueid": "eve-unique-002",
            "username": "eve",
            "nasipaddress": "4.4.4.4",
            "acctstarttime": (now - timedelta(days=1)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctstoptime": (now - timedelta(hours=12)).strftime("%Y-%m-%d %H:%M:%S"),
            "acctsessiontime": 43200,
            "acctinputoctets": 2000000000,
            "acctoutputoctets": 25000000000,
            "framedipaddress": "10.0.0.3",
            "acctterminatecause": "User-Request",
        },
    ]

    for record in radacct_records:
        columns = ", ".join(record.keys())
        placeholders = ", ".join(["%s"] * len(record))
        sql = f"INSERT INTO {rad_tables.radacct} ({columns}) VALUES ({placeholders})"
        cursor.execute(sql, tuple(record.values()))

cursor.close()

db_connection.commit()
db_connection.close()
