from pydantic import BaseModel


class RadTables(BaseModel):
    nas: str = "nas"
    # nasreload
    radacct: str = "radacct"
    radcheck: str = "radcheck"
    radgroupcheck: str = "radgroupcheck"
    radgroupreply: str = "radgroupreply"
    # radpostauth <- records generated by FreeRadius after authentication [not-managed]
    radreply: str = "radreply"
    radusergroup: str = "radusergroup"
    radhuntgroup: str = "radhuntgroup"
